/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.snippts.Snippts;

import static com.mycompany.snippts.Snippts.Login.un;
import static com.mycompany.snippts.Snippts.MainPage.s_title;
import static com.mycompany.snippts.Snippts.MainPage.edit;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author ieucd
 */
public class AddSum extends javax.swing.JFrame {
    Connection con=Db.con();
    PreparedStatement stmt=null;
    ResultSet rs=null;
    int saveCheck=0;
    
    public AddSum() {
        initComponents();
        if(edit==1){
            checkRepos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        label_quote = new javax.swing.JLabel();
        label_snippet = new javax.swing.JLabel();
        tfas_bt = new javax.swing.JTextField();
        tfas_an = new javax.swing.JTextField();
        labelas_bt = new javax.swing.JLabel();
        labelas_an = new javax.swing.JLabel();
        labelas_summary = new javax.swing.JLabel();
        buttonas_save = new javax.swing.JButton();
        buttonas_back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfas_sum = new javax.swing.JTextArea();
        buttonas_delete = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 188, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        label_quote.setBackground(new java.awt.Color(154, 188, 255));
        label_quote.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        label_quote.setForeground(new java.awt.Color(0, 0, 0));
        label_quote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quote.setText("Book Summaries");

        label_snippet.setBackground(new java.awt.Color(154, 188, 255));
        label_snippet.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_snippet.setForeground(new java.awt.Color(0, 0, 0));
        label_snippet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_snippet.setText("Snippets");

        tfas_bt.setBackground(new java.awt.Color(255, 255, 255));
        tfas_bt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfas_bt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfas_bt.setToolTipText("");
        tfas_bt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfas_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfas_btActionPerformed(evt);
            }
        });

        tfas_an.setBackground(new java.awt.Color(255, 255, 255));
        tfas_an.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfas_an.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfas_an.setToolTipText("");
        tfas_an.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfas_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfas_anActionPerformed(evt);
            }
        });

        labelas_bt.setBackground(new java.awt.Color(154, 188, 255));
        labelas_bt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelas_bt.setForeground(new java.awt.Color(0, 0, 0));
        labelas_bt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelas_bt.setText("Book Title:");

        labelas_an.setBackground(new java.awt.Color(154, 188, 255));
        labelas_an.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelas_an.setForeground(new java.awt.Color(0, 0, 0));
        labelas_an.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelas_an.setText("Author Name:");

        labelas_summary.setBackground(new java.awt.Color(154, 188, 255));
        labelas_summary.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelas_summary.setForeground(new java.awt.Color(0, 0, 0));
        labelas_summary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelas_summary.setText("Summary:");

        buttonas_save.setBackground(new java.awt.Color(178, 190, 181));
        buttonas_save.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonas_save.setForeground(new java.awt.Color(0, 0, 0));
        buttonas_save.setText("Save");
        buttonas_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonas_saveActionPerformed(evt);
            }
        });

        buttonas_back.setBackground(new java.awt.Color(178, 190, 181));
        buttonas_back.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonas_back.setForeground(new java.awt.Color(0, 0, 0));
        buttonas_back.setText("Back");
        buttonas_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonas_backActionPerformed(evt);
            }
        });

        tfas_sum.setBackground(new java.awt.Color(255, 255, 255));
        tfas_sum.setColumns(20);
        tfas_sum.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tfas_sum.setForeground(new java.awt.Color(0, 0, 0));
        tfas_sum.setLineWrap(true);
        tfas_sum.setRows(5);
        jScrollPane2.setViewportView(tfas_sum);

        buttonas_delete.setBackground(new java.awt.Color(178, 190, 181));
        buttonas_delete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonas_delete.setForeground(new java.awt.Color(0, 0, 0));
        buttonas_delete.setText("Delete");
        buttonas_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonas_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(label_quote)))
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelas_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfas_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonas_back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonas_delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonas_save))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelas_summary)
                                .addComponent(labelas_an))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfas_an, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_quote)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfas_bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelas_bt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfas_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelas_an))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelas_summary))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonas_save)
                    .addComponent(buttonas_back)
                    .addComponent(buttonas_delete))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfas_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfas_anActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfas_anActionPerformed

    private void buttonas_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonas_saveActionPerformed
        // Save and remain on AddSum
        String bt=tfas_bt.getText();
        String an=tfas_an.getText();
        String sum=tfas_sum.getText();
        if(bt.isBlank()||an.isBlank()||sum.isBlank()){
            JOptionPane.showMessageDialog(rootPane,"Please make sure all fields are filled!");
        }
        else{
            try{
                //To check for duplicate summaries with same title
                String sql="SELECT * FROM SUMMARIES WHERE USERNAME=? AND TITLE=? AND AUTHOR=?";
                stmt=con.prepareCall(sql);
                stmt.setString(1,un);
                stmt.setString(2,bt);
                stmt.setString(3, an);
                rs=stmt.executeQuery();
                if(rs.next()){
                    int a=JOptionPane.showConfirmDialog(rootPane,"You already have a summary for this title, do you want to update it? ( If no, a new summary will be created.)");
                    if(a==JOptionPane.YES_OPTION){
                        String sql3="UPDATE SUMMARIES SET SUMMARY=?, AUTHOR=? WHERE USERNAME=? AND TITLE=?;";
                        stmt=con.prepareStatement(sql3);
                        stmt.setString(1, sum);
                        stmt.setString(2, an);
                        stmt.setString(3, un);
                        stmt.setString(4, bt);
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Saved!");
                        saveCheck=1;
                    }
                    else if(a==JOptionPane.NO_OPTION){
                        try{
                        //To store summary into database under summaries table
                        String sql2="INSERT INTO SUMMARIES(USERNAME,TITLE,AUTHOR,SUMMARY) VALUES(?,?,?,?)";
                        stmt=con.prepareStatement(sql2);
                        stmt.setString(1,un);
                        stmt.setString(2,bt);
                        stmt.setString(3, an);
                        stmt.setString(4,sum);
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Saved!");
                        saveCheck=1;
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane, "Please Try again!");
                        System.out.println(e);
                    }
                    } 
                }
                else{
                    try{
                        //To store summary into database under summaries table
                        String sql1="INSERT INTO SUMMARIES(USERNAME,TITLE,AUTHOR,SUMMARY) VALUES(?,?,?,?)";
                        stmt=con.prepareStatement(sql1);
                        stmt.setString(1,un);
                        stmt.setString(2,bt);
                        stmt.setString(3, an);
                        stmt.setString(4,sum);
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Saved!");
                        this.setVisible(false);
                        new MainPage().setVisible(true);
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane, "Please Try again!");
                        System.out.println(e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Please Try again!");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_buttonas_saveActionPerformed
    public void checkRepos(){
        if(s_title!=null){
            try {
                String sql6="SELECT TITLE, AUTHOR, SUMMARY FROM SUMMARIES WHERE USERNAME=? AND TITLE=?;";
                stmt=con.prepareCall(sql6);
                stmt.setString(1, un);
                stmt.setString(2, s_title);
                rs=stmt.executeQuery();
            if(rs.next()){
                tfas_bt.setText(rs.getString(1));
                tfas_an.setText(rs.getString(2));
                tfas_sum.setText(rs.getString(3));
            }
        } catch (Exception ex) {
            System.out.println(ex);
           }
       }
    }
    private void buttonas_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonas_backActionPerformed
        // Back to MainPage
        String bt=tfas_bt.getText();
        if(bt.isBlank()){
            saveCheck=0;
        }
        if(saveCheck==0){
            JOptionPane.showMessageDialog(rootPane, "Remember to save your summary! ");
            saveCheck=1;
        }
        else{
            this.setVisible(false);
            new MainPage().setVisible(true);
        }
    }//GEN-LAST:event_buttonas_backActionPerformed

    private void buttonas_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonas_deleteActionPerformed
        String bt=tfas_bt.getText();
        String an=tfas_an.getText();
        String sum=tfas_sum.getText();
        if(bt.isBlank()||an.isBlank()||sum.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "There is nothing to delete!");
            saveCheck=1;
            buttonas_back.doClick();
        }
        else{
            int b= JOptionPane.showConfirmDialog(rootPane, "Confirm Delete: ");
            if(b==JOptionPane.YES_OPTION){
                try{
                    String sql4="DELETE FROM SUMMARIES WHERE USERNAME=? AND TITLE=?;";
                    stmt=con.prepareStatement(sql4);
                    stmt.setString(1,un);
                    stmt.setString(2,bt);
                    stmt.executeUpdate();
                try{
                    String sql5="SET @AUTONO:=0; UPDATE SUMMARIES SET NO= @AUTONO:=(@AUTONO+1); ALTER TABLE SUMMARIES auto_increment=1;";
                    stmt=con.prepareStatement(sql5);
                    stmt.executeUpdate();
                }
                catch(SQLException ignored){
                    
                }
                    JOptionPane.showMessageDialog(rootPane,"Summary Deleted!");
                    this.setVisible(false);
                    new MainPage().setVisible(true);
            }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Try Again");
                    System.out.println(e);
            }
        }
            else if(b==JOptionPane.NO_OPTION){
                buttonas_save.doClick();
            }
        } 
    }//GEN-LAST:event_buttonas_deleteActionPerformed

    private void tfas_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfas_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfas_btActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonas_back;
    private javax.swing.JButton buttonas_delete;
    private javax.swing.JButton buttonas_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_quote;
    private javax.swing.JLabel label_snippet;
    private javax.swing.JLabel labelas_an;
    private javax.swing.JLabel labelas_bt;
    private javax.swing.JLabel labelas_summary;
    private javax.swing.JTextField tfas_an;
    private javax.swing.JTextField tfas_bt;
    private javax.swing.JTextArea tfas_sum;
    // End of variables declaration//GEN-END:variables
}
