/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.snippts.Snippts;

import static com.mycompany.snippts.Snippts.Login.un;
import java.sql.*;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author ieucd
 */
public class MainPage extends javax.swing.JFrame {
    public static String s_title;
    public static int edit=0;
    /**
     * Creates new form MainPage
     */
    Connection con=Db.con();
    PreparedStatement stmt=null;
    ResultSet rs=null;
    
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_quote = new javax.swing.JLabel();
        label_snippet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonmp_logout = new javax.swing.JButton();
        buttonmp_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listmp_summaries = new javax.swing.JList<>();
        buttonmp_refresh = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        jButton1.setText("jButton1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 188, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        label_quote.setBackground(new java.awt.Color(154, 188, 255));
        label_quote.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        label_quote.setForeground(new java.awt.Color(0, 0, 0));
        label_quote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quote.setText("Book Summaries");

        label_snippet.setBackground(new java.awt.Color(154, 188, 255));
        label_snippet.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_snippet.setForeground(new java.awt.Color(0, 0, 0));
        label_snippet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_snippet.setText("Snippets");

        jLabel1.setBackground(new java.awt.Color(154, 188, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome "+un+" !");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ieucd\\Downloads\\176-1760995_user-icon-png.png")); // NOI18N
        jLabel2.setText("jLabel2");

        buttonmp_logout.setBackground(new java.awt.Color(178, 190, 181));
        buttonmp_logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonmp_logout.setForeground(new java.awt.Color(0, 0, 0));
        buttonmp_logout.setText("Log Out");
        buttonmp_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonmp_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmp_logoutActionPerformed(evt);
            }
        });

        buttonmp_new.setBackground(new java.awt.Color(178, 190, 181));
        buttonmp_new.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonmp_new.setForeground(new java.awt.Color(0, 0, 0));
        buttonmp_new.setText("New");
        buttonmp_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonmp_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmp_newActionPerformed(evt);
            }
        });

        listmp_summaries.setBackground(new java.awt.Color(154, 188, 255));
        listmp_summaries.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "My Summaries", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        listmp_summaries.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        listmp_summaries.setForeground(new java.awt.Color(0, 0, 0));
        listmp_summaries.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Refresh to load summaries" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listmp_summaries.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listmp_summaries.setToolTipText("");
        listmp_summaries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listmp_summaries.setSelectionBackground(new java.awt.Color(193, 225, 193));
        listmp_summaries.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listmp_summariesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listmp_summaries);

        buttonmp_refresh.setBackground(new java.awt.Color(154, 188, 255));
        buttonmp_refresh.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonmp_refresh.setForeground(new java.awt.Color(0, 0, 0));
        buttonmp_refresh.setText("Refresh");
        buttonmp_refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 103, 122)));
        buttonmp_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmp_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(label_quote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonmp_refresh))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonmp_new, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonmp_logout)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonmp_logout)
                    .addComponent(buttonmp_new))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quote)
                    .addComponent(buttonmp_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonmp_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmp_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonmp_logoutActionPerformed

    private void buttonmp_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmp_newActionPerformed
        // TODO add your handling code here:
        edit=0;
        this.setVisible(false);
        new AddSum().setVisible(true);
    }//GEN-LAST:event_buttonmp_newActionPerformed

    private void listmp_summariesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listmp_summariesValueChanged
        // when list clicked
        edit=1;
        s_title=(String)listmp_summaries.getSelectedValue();
        try{
            String sql2="SELECT * FROM SUMMARIES WHERE USERNAME=? AND TITLE=?;";
            stmt=con.prepareCall(sql2);
            stmt.setString(1,un);
            stmt.setString(2,s_title);
            rs= stmt.executeQuery();
            if(rs.next()){
                    this.setVisible(false);
                    new AddSum().setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try Again!");
            System.out.println(e);
        }
    }//GEN-LAST:event_listmp_summariesValueChanged

    private void buttonmp_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmp_refreshActionPerformed
        // To display titles in summary repository
        listmp_summaries.removeAll();
        DefaultListModel<String> data=new DefaultListModel<>();
        try{
            String sql="SELECT TITLE FROM SUMMARIES WHERE USERNAME=? ORDER BY CREATED DESC;";
            stmt=con.prepareCall(sql);
            stmt.setString(1,un);
            rs=stmt.executeQuery();
            while(rs.next()){
                data.addElement(rs.getString(1));
            }
            listmp_summaries.setModel(data);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Try Again!");
            System.out.println(e);
        }
    }//GEN-LAST:event_buttonmp_refreshActionPerformed
    

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonmp_logout;
    private javax.swing.JButton buttonmp_new;
    private javax.swing.JButton buttonmp_refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_quote;
    private javax.swing.JLabel label_snippet;
    private javax.swing.JList<String> listmp_summaries;
    // End of variables declaration//GEN-END:variables
}
