/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.snippts.Snippts;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ieucd
 */
public class SignUp extends javax.swing.JFrame {
        Connection con=Db.con();
        PreparedStatement stmt=null;
        public String user;
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        label_username1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_snippet = new javax.swing.JLabel();
        label_quote = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_cfmpassword = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        tfsu_username = new javax.swing.JTextField();
        tfsu_cfmpassword = new javax.swing.JTextField();
        tfsu_password = new javax.swing.JTextField();
        button_signin = new javax.swing.JButton();
        label_rule = new javax.swing.JLabel();
        label_bck2login = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(154, 188, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Snippets");

        jLabel2.setBackground(new java.awt.Color(154, 188, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book Summaries");

        jLabel3.setBackground(new java.awt.Color(154, 188, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Snippets");

        jLabel4.setBackground(new java.awt.Color(154, 188, 255));
        jLabel4.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Book Summaries");

        jLabel5.setBackground(new java.awt.Color(154, 188, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Snippets");

        jLabel6.setBackground(new java.awt.Color(154, 188, 255));
        jLabel6.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Book Summaries");

        jLabel7.setBackground(new java.awt.Color(154, 188, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Snippets");

        jLabel8.setBackground(new java.awt.Color(154, 188, 255));
        jLabel8.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Book Summaries");

        jLabel12.setBackground(new java.awt.Color(154, 188, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Username :");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        label_username1.setBackground(new java.awt.Color(154, 188, 255));
        label_username1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_username1.setForeground(new java.awt.Color(0, 0, 0));
        label_username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_username1.setText("Username :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 188, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        label_snippet.setBackground(new java.awt.Color(154, 188, 255));
        label_snippet.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_snippet.setForeground(new java.awt.Color(0, 0, 0));
        label_snippet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_snippet.setText("Snippets");

        label_quote.setBackground(new java.awt.Color(154, 188, 255));
        label_quote.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        label_quote.setForeground(new java.awt.Color(0, 0, 0));
        label_quote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_quote.setText("Book Summaries");

        jLabel11.setBackground(new java.awt.Color(154, 188, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sign Up");

        label_password.setBackground(new java.awt.Color(154, 188, 255));
        label_password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_password.setForeground(new java.awt.Color(0, 0, 0));
        label_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_password.setText("Password :");

        label_cfmpassword.setBackground(new java.awt.Color(154, 188, 255));
        label_cfmpassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_cfmpassword.setForeground(new java.awt.Color(0, 0, 0));
        label_cfmpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cfmpassword.setText("Confirm Password :");

        label_username.setBackground(new java.awt.Color(154, 188, 255));
        label_username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(0, 0, 0));
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_username.setText("Username :");

        tfsu_username.setBackground(new java.awt.Color(255, 255, 255));
        tfsu_username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfsu_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfsu_username.setToolTipText("");
        tfsu_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tfsu_cfmpassword.setBackground(new java.awt.Color(255, 255, 255));
        tfsu_cfmpassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfsu_cfmpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfsu_cfmpassword.setToolTipText("");
        tfsu_cfmpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tfsu_password.setBackground(new java.awt.Color(255, 255, 255));
        tfsu_password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tfsu_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfsu_password.setToolTipText("");
        tfsu_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        button_signin.setBackground(new java.awt.Color(138, 209, 159));
        button_signin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        button_signin.setForeground(new java.awt.Color(0, 0, 0));
        button_signin.setText("Sign in");
        button_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signinActionPerformed(evt);
            }
        });

        label_rule.setBackground(new java.awt.Color(154, 188, 255));
        label_rule.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_rule.setForeground(new java.awt.Color(0, 0, 0));
        label_rule.setText("Username and Password contain maximum 12 characters  ");

        label_bck2login.setBackground(new java.awt.Color(154, 188, 255));
        label_bck2login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_bck2login.setForeground(new java.awt.Color(19, 53, 168));
        label_bck2login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bck2login.setText("I have an account");
        label_bck2login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bck2login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_bck2loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_cfmpassword)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_password, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_username)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsu_username, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(tfsu_cfmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(tfsu_password, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(162, 162, 162))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(label_quote)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button_signin)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(214, 214, 214))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_bck2login)
                    .addComponent(label_rule))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(label_snippet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_quote)
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username)
                    .addComponent(tfsu_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password)
                    .addComponent(tfsu_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cfmpassword)
                    .addComponent(tfsu_cfmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_signin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_rule)
                .addGap(31, 31, 31)
                .addComponent(label_bck2login)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signinActionPerformed
        // Sign in + save into user_database
        String user=tfsu_username.getText();
        String pass=tfsu_password.getText();
        String cfmpass=tfsu_cfmpassword.getText();
        if(!pass.equals(cfmpass)){
            JOptionPane.showMessageDialog(rootPane, "Your passwords do not match!");
        }
        else if(user.length()<4||pass.length()<4){
            JOptionPane.showMessageDialog(rootPane,"Password or Username too short (At least 4 characters) !");
        }
        else if(user.length()>12||pass.length()>12){
            JOptionPane.showMessageDialog(rootPane, "Length of Username and Password is maximum 12 characters!");
        }
        else{
            try{
                String sql="INSERT INTO USER_DATABASE(USERNAME,PASSWORD)"+ "VALUES(?,?);";
                stmt=con.prepareStatement(sql);
                stmt.setString(1, user);
                stmt.setString(2, pass);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(rootPane,"Your account has been created, please Log In!");
                tfsu_username.setText("");
                tfsu_password.setText("");
                tfsu_cfmpassword.setText("");
                this.setVisible(false);
                new Login().setVisible(true);
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(rootPane,"Username taken try again with a different username!");
            }
        }
        
    }//GEN-LAST:event_button_signinActionPerformed

    private void label_bck2loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_bck2loginMouseClicked
        // Back to login page
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_label_bck2loginMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_signin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_bck2login;
    private javax.swing.JLabel label_cfmpassword;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_quote;
    private javax.swing.JLabel label_rule;
    private javax.swing.JLabel label_snippet;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel label_username1;
    private javax.swing.JTextField tfsu_cfmpassword;
    private javax.swing.JTextField tfsu_password;
    private javax.swing.JTextField tfsu_username;
    // End of variables declaration//GEN-END:variables
}
